# 🍔 The Burger Lab: Customer Sentiment Analysis

### Executive Summary
* **Objective:** Automate the categorization of unstructured text reviews to determine overall customer satisfaction and identify operational bottlenecks.
* **Methodology:** Built a custom Natural Language Processing (NLP) algorithm in Python to tag raw text reviews as Positive, Negative, or Neutral based on keyword presence.
* **Key Finding:** The restaurant has a critical **40% negative feedback rate**, primarily driven by complaints regarding kitchen QA (cold/undercooked food) and slow wait times. 
* **Recommendation:** Immediate operational intervention in the kitchen is required before leadership focuses on further marketing or expansion.
---

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('burger_lab_reviews.csv')

In [3]:
df

   Review_ID                                        Review_Text
0        201  The new spicy chicken sandwich is absolutely a...
1        202  Terrible experience. The fries were cold and t...
2        203   It was okay. Nothing special but not bad either.
3        204  Best burger I have ever had in this city. Grea...
4        205  Waited 45 minutes for my food. So slow and wor...
5        206      The classic cheeseburger is good. I liked it.
6        207  Completely awful. The meat tasted weird and th...
7        208        Decent food for the price. Might come back.
8        209   I love this place! Always fresh and great staff.
9        210                         Horrible. Do not eat here.

In [10]:
df['Review_Text']=df['Review_Text'].str.lower()

In [11]:
df

   Review_ID                                        Review_Text
0        201  the new spicy chicken sandwich is absolutely a...
1        202  terrible experience. the fries were cold and t...
2        203   it was okay. nothing special but not bad either.
3        204  best burger i have ever had in this city. grea...
4        205  waited 45 minutes for my food. so slow and wor...
5        206      the classic cheeseburger is good. i liked it.
6        207  completely awful. the meat tasted weird and th...
7        208        decent food for the price. might come back.
8        209   i love this place! always fresh and great staff.
9        210                         horrible. do not eat here.

In [14]:
def sentiment_analyzer(text):
    positive = ['amazing', 'delicious', 'best', 'great', 'good', 'love']
    negative = ['terrible', 'cold', 'undercooked', 'worst', 'awful', 'horrible']
    
    if any(word in text for word in positive):
        return 'Positive'
    elif any (word in text for word in negative):
        return 'Negative'
    else:
        return 'Neutral'

In [15]:
df['Sentiment']=df['Review_Text'].apply(sentiment_analyzer)

In [16]:
df

   Review_ID                                        Review_Text Sentiment
0        201  the new spicy chicken sandwich is absolutely a...  Positive
1        202  terrible experience. the fries were cold and t...  Negative
2        203   it was okay. nothing special but not bad either.   Neutral
3        204  best burger i have ever had in this city. grea...  Positive
4        205  waited 45 minutes for my food. so slow and wor...  Negative
5        206      the classic cheeseburger is good. i liked it.  Positive
6        207  completely awful. the meat tasted weird and th...  Negative
7        208        decent food for the price. might come back.   Neutral
8        209   i love this place! always fresh and great staff.  Positive
9        210                         horrible. do not eat here.  Negative

In [17]:
total_sentiment=df['Sentiment'].value_counts()

In [18]:
print('Burger Lab Customer Sentiment')
print(total_sentiment)

Burger Lab Customer Sentiment
Sentiment
Positive    4
Negative    4
Neutral     2
Name: count, dtype: int64